name: Run Airflow DAG

on:
  workflow_dispatch: # Pozwala na ręczne uruchomienie workflow

jobs:
  run_airflow_dag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          docker-compose up -d
          echo "Waiting for Airflow to be healthy..."
          until $(curl --output /dev/null --silent --head --fail http://localhost:8080/health); do
            printf '.'
            sleep 5
          done
          echo "Airflow Webserver is up and running."

      - name: Trigger Airflow DAG
        run: |
          curl -X POST "http://localhost:8080/api/v1/dags/check_duplicates_dag/dagRuns" \
          -H "Content-Type: application/json" \
          --user "admin:admin" \
          -d '{"conf": {}}'

      - name: Shut down Docker Compose
        run: docker-compose down
