name: Run Airflow DAG

on:
  workflow_dispatch: # Pozwala na ręczne uruchomienie workflow

jobs:
  run_airflow_dag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Set up Docker Compose
        run: |
          docker-compose up -d
          echo "Waiting for Airflow Webserver to start..."
          timeout=60 # Czas oczekiwania na uruchomienie Airflow w sekundach (5 minut)
          while ! curl -s http://localhost:8080 | grep -q "Log In"; do
            if [ $timeout -le 0 ]; then
              echo "Timeout waiting for Airflow to start"
              exit 0
            fi
            echo "Still waiting for Airflow..."
            sleep 10
            timeout=$((timeout - 5))
          done
          echo "Airflow Webserver is up and running."

      - name: Trigger Airflow DAG
        run: |
          curl -X POST "http://localhost:8080/api/v1/dags/check_duplicates_dag/dagRuns" \
          -H "Content-Type: application/json" \
          --user "admin:admin" \
          -d '{"conf": {}}'

      - name: Shut down Docker Compose
        run: docker-compose down
